#! /bin/sh

### BEGIN INIT INFO
# Provides:          madroniusbotd
# Required-Start:    $network $local_fs
# Required-Stop:     $network $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:
# Short-Description: Start Madronius Bot
### END INIT INFO

# Init and get environment variables
PATH=/sbin:/usr/sbin:/bin:/usr/bin

. /lib/lsb/init-functions

[ -f /home/madronius/.env ] && . /home/madronius/.env
[ -z "$PROJECT_PATH" ] && PROJECT_PATH=/home/madronius/madroniusbot
[ -z "$PROJECT_BIN" ] && PROJECT_BIN=MadroniusBot/bin/Release/netcoreapp3.1/MadroniusBot.dll
[ -z "$DOTNET_PATH" ] && DOTNET_PATH=/home/madronius/.dotnet

set -e

# Functions
start() {
    cd "$PROJECT_PATH"
    runuser -u madronius "$DOTNET_PATH/dotnet" "$PROJECT_BIN" >> /var/log/MadroniusBot.log &
}

stop() {
    pkill -f "MadroniusBot"
}

restart() {
    stop
    start
}



# Carry out above functions when asked to by the system
case "$1" in
  start)
    log_daemon_msg "Starting Madronius Bot.."
    start
    log_end_msg 0
    ;;
  stop)
    log_daemon_msg "Stopping Madronius Bot.."
    stop
    log_end_msg 0
    ;;
  restart)
    log_daemon_msg "Restarting Madronius Bot.."
    restart
    log_end_msg 0
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
    ;;
esac

exit 0
